name: Run Automation Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Npx setup
        run: npx playwright install 

      - name: Run tests
        run: npx playwright test
