name: Run Automation Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and missing libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libvpx5 \
            libopus0 \
            libharfbuzz0b \
            libflite1 \
            libGLESv2-2
          npm install

      - name: Npx setup
        run: npx playwright install 
i
      - name: Run tests
        run: npx playwright test
