name: Run Automation Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and missing libraries
        run: |
          sudo add-apt-repository -y ppa:jeffreyratcliffe/ppa
          sudo apt-get update
          sudo apt-get install -y \
            libvpx-dev \
            libopus-dev \
            libharfbuzz-dev \
            libgles2-mesa-dev \
            libx264-dev \
            libsoup2.4-dev \
            woff2 \
            libevent-dev \
            libgstreamer-plugins-base1.0-dev \
            libgstreamer1.0-dev \
            libhyphen-dev \
            #libmanette-dev \
            #libx264-dev
          npm install

      - name: Npx setup
        run: npx playwright install 

      - name: Run tests
        run: npx playwright test
